### PR TITLE
Add page library, management feature flags for page builder

### PR DESCRIPTION
**Pull request by mpeels**
Adds the following feature flags to the configuration passed to the nbs-gateway and modernization-api at startup.

The intent is to allow the feature flagging of the `Page Library` and `Page Management` screens.

```
pageBuilder:
  page:
    library:
      enabled: "true"
    management:
      enabled: "true"
```

### CODE REVIEW

**Review by szamfir — CHANGES_REQUESTED** [review]
Currently int1 and test use the head of the main branch and so any chart changes should be reflected in values-int1.yaml (already done) and values-test2.yaml.

**Comment by adamloup-enquizit** [comment]
> Currently int1 and test use the head of the main branch and so any chart changes should be reflected in values-int1.yaml (already done) and values-test2.yaml.

This is an additive change where we would want TEST to use the default configuration values (disabled).  The feature flags will be turned on for INT1.  Are the values layered?  Where `values.yaml` is applied first and then the `values-{environment}.yml`.  I know we talked about this but can't recall if it ever ended up being implemented.

**Review by szamfir — COMMENTED** [review]
It is just one file being picked up per environment. values.yaml is default that is not aimed at a particular environment

**Review by szamfir — APPROVED** [review]
Lgtm

**Pull request merged**
